# Fisheries Ecology and Management Walters and Martell (2004) 

## Changing Objectives and Emerging Assessment Methods

### The Role of Predictive Models
Predictive models are needed because management agencies need to make decisions about what is preferred, and what might happen in the future. Thus, we need to choose some sort of model to make these decisions. In general, we don't need predictions to be unconditional of the future, but rather we generally need our predictions for policy to answer whether A is better than B, and which one is a better bet in the future (we only really need to know about relative performance). So if we were to get asked how can we manage fish without knowing how many are there, we can say "for a wide range of scenarios, policy X does better despite uncertainties in the system, in a simulation scenario". Additionally, predictions can be made/policy choices can be made to have responses to change - i.e., taking a fixed proportion of harvest vs. fixed catch. 

### Approaches to Prediction of Policy Impact
1. Conventional Wisdom and Dogma - Basically, managers will ignore policies that they deem as atypical and continue to operate as if no new evidence has been presented, especially when something does not align with their understanding of a system. 
1. Trend Extrapolation - Using historical data to forecast the future, either by eye or with time-series methods. However, this really only works when there are small gradual changes - fisheries can change rapidly. Additionally, this approach might not be appropriate if the index you are using is not representative (catch, CPUE, etc),
1. Empirical Models based on past experience - using comparative data from other species of systems to understand how those respond to policies and how that might apply to your system.
1. Reductionist Modelling - using tautologies and assumptions to create mathematical models, which keeps modelled components and associated predictions tractable to use and understand. But several things can go awry, namely, if you make the incorrect assumptions about functional forms, the propagation of error in previous states to future states can compound, etc.

### Experimental Management
The approach for experimental management is to create a wide range of policy options that are robust (maybe via simulation) and then apply these options to the system across some sort of treatment, to understand their relative impact. But generally, people don't like this approach because it's 'risky' and people generally prefer using models to figure out what options we should use.

#### Decision Making Under Uncertainty
Uncertainty in our predictions are a result of 3 factors. 1) We never measure anything precisely, 2) we don't know the rules of change and how the system will respond, and 3) environmental impacts on predictions are not well known or understood. So even if we can measure things precisely, we never know how the environment will respond, resulting in substantial uncertainty in our predictions. 

In general, making decisions is hard (duh) irrespective of whether you have good predictions or not, just simply given the uncertainty you have in the system. We are often paralyzed by the indecision (or decision) of whether to make a decisive action (e.g., stop fishing) or to 'wait and see'.

### Ecological Basis for Sustainable Harvesting
In general, populations can grow at some rate $r$ and are generally mediated by density-dependent effects, rather than only density-independent effects. Given that there is often a compensatory mechanism in many animal populations, harvesting the population at a modest rate allows for an improved survival or fecundity, given a reduction in the population, and forms the ecological basis for sustainable harvesting. 

Some typical responses of populations have been observed, which include:
1. For semelparous species, fecundity remains fairly constant, or declines when there are strong declines in old fish (no compensatory response)
1. Survival rates for old individuals generally do not show compensatory responses,
1. Juvenile survival rates show compensatory responses and can be independent of the number of eggs produced.

In terms of a surplus production model, we typically think of growth potentially having a larger effect on production of biomass, with a stronger influence that recruitment and we are generally interested in modifying the harvest rate to see what our total gains in production can be $Y_t = u_tN_tw$. However, its important to note that while increasing harvest rates helps with the compensatory response of the population, it also decreases your average abundance as well as your average weight of the population (because you are truncating your age-structure, and there are less old big fish left in the population). Nonetheless, a truncation in age-structure leads to more younger fast growing fish, which in turn leads to a higher growth rate on a per-capita basis. However, this is misleading, because we still need to account for the total number of individuals, irrespective of what happens to per-capita increases in growth rates.

Some other notes on simple logistic growth/surplus production models. Although these equations are simple $N_t = r_{t-1}N_{t-1}$ they do not necessarily indicate that all individuals in the population are the same. This is because the number of individuals $N_t$ are composed of a mixture of ages and sees, and multiplying this mixture by some rate value gives the average total production of the number of individuals in the following year (i.e., $r$ is a per-capita rate that is applied to the entire mixture).

Some other notes on the use of instantaneous rates vs. multiplying by constants. We tend to use instataneous rates because changes in fisheries can happen rapidly over a short period (e.g., pulse fishery), which makes using rate changes more convenient ($N_{t+1} = N_te^{-Z}$) than multiplying by some constant ($N_{t+1} = N_tS$). Additionally, instantaneous rates of change allow us to partition mortality into other components (fishing, predation) and allow us to calculate losses in the population due to some specific factor.

### Synthesis
1. Predictive models are needed because management agencies need to understand decisions between policy A and policy B such that we know which option is a better bet for the future,
1. We need to make decisions under uncertainty, where uncertainty arises given imprecise measurements, assumptions modellers make, uncertainty about future conditions and how stocks will respond to policies. In general, managers are confronted with this idea of decisive action vs. inaction. Nonetheless, despite these uncertainties and not being able to count the precise number of fish out there, we can use simulations and models to figure out what policy option might be the best bet in the future, given a range of uncertainties.
1. There is an ecological basis for harvesting, which generally revolves around the idea of compensatory responses - wherein we can get gains in production by fishing the population away from its carrying capacity. Harvesting the population at a modest rate can allow for improved survival of juveniles, and less commonly, improved fecundity in species. 


## Trade-offs in Fisheries Management
The key goal of fisheries management is to expose trade-offs within the system and associated conflicting objectives, and to develop ways in which we can successfully work around and within these trade-offs/conflicting objectives. 

Some common tradeoffs in fisheries include:
1. abundance of target species and fishing effort,
1. harvest today vs. long term (e.g., current sablefish situation),
1. harvest of productive and non-productive stocks,
1. profit versus employment,
1. expenditure on fisheries resources vs. others,
1. harvest of valuable versus abundance species, 
1. fishing practices that are not selective vs. selective,
1. monitoring vs. basic ecological research,
1. developing new data monitoring and assessment methods vs. gathering data,
1. investment in enforcement vs. research, and
1. interesting research vs. research that seeks to manage a system.

### Tradeoff relationships and policy choices
Generally, the authors predict that two types of patterns will emerge when comparing traadeoffs between two policy choices.
1. Convex set, where one value can be increased without impacting the other value that much, 
1. Concave set, where an increase in one value leads to a disproportionate decrease in another value, and
1. Linear set, an increase in one value leads to a proportional decrease in another value.

Fisheries that tend to operate with a suboptimal policy occurs because:
1. something has been left out of the tradeoff calculation,
1. there are hidden objectives not visible in a 2D graph,
1. someone isn't doing their job right.

Typically in fisheries, we have arguments that invovle two types of objective functions:
1. linear - $V = w_1X + w_2Y$ where $V$ is the total value, $X, Y$ are conflicting measures and $w$ are weights placed upon those measures,
1. logarithmic - $V = X^{w1} + Y^{w_2}$

Typically, linear tradeoffs occur when we are able to freely tradeoff between choices without prejudice about extreme values, while logarithmic tradeoffs occur when extreme values for certain choices are seen as illegal or unfair or destructive. An example given in the book is that small increments in income are seen as favorable, but when your income is large, increases do not necessarily have as much value anymore.

### Short term vs. long term values
A common short term vs. long term value in fisheries revolves around the value of harvesting now vs. harvesting later. In general, harvesters will want to constrain fishing such as to provide a reasonable harvest this year without reducing the stock below a sustainable level for which will maximize the average surplus production in a given year (i.e., allow for fishing and keep the stock at a sustainable level so its able to produce good surplus in future years). But this decision is much harder when a stock has been overfished and requires some form of rebuilding (closures or little fishing allowed), because some of the benefits reaped from not allowing fishing might not apply to current harvesters and allowing for little fishing will severely compromise/prolong the recovery process.

#### Why and what to do when harvesters oppose rebuilding plans?
1. Harvesters might oppose rebuilding plans because their short term pain does not necessarily translate to long term gain, and economics show that allowing for some fishing is way more beneficial. To resolve this issue, the authors propose instituting some form of property right so that they can reap the benefits when time comes,
1. There is no assurance about the increases of catches following a rebuild period because of uncertainty and the precatuionary principle. Harvesters need to see firm decision rules as to how catches will increase in response to surveys, etc.
1. In a multi-species fishery, rebuilding leads to less of the abundant fish being caught in order to rebuild a depleted stock. Thus, regulators need to identify species that are actually endangered vs. those that are fished less than optimaly on a single-species basis.
1. The gain in the long term might not be that attractive and gains in the short term are more beneficial. Management plans here should balance expected benefits to costs and if the expected costs are much larger, then harvesters should be provided with financial benefits of some form.
1. The definition of a depleted stock is incorrect - by allowing harvesters to be part of the process, this situation might be circumvented and allows them to build confidence in the assessment process.

### Trade offs between biodiversity and productivity
Tradeoffs between biodiversity and production are not simple and can be grossly overestimated in terms of their responses. In particular, allowing for increased harvest of a given species can have several different responses to their predators (increase, decrease, or exponential decrease). Exploring these tradeoffs in an ecosystem model has sometimes even shown that we should cull the predators to maximize profits. Some of the mixed-stock fisheries in salmon face a lot of these problems - whether to protect your weak stocks and minimize catch or to disregard the weak stocks and just allow harvest. Some proposed solutions have been to close fisheries in certain areas or allow for temporal lags in fishing 

### Economic efficiency vs. diversity of employment oppurtunities
Obviously there are tradeoffs between economic efficiency and diversity. In general, a lot of these tradeoffs have been approached through the lens of an economist, where they noticed that profits were being spread between too many people and recommended that we scale back the fleet size, increase efficiency, and allow for some form of ITQ fishing. However, this is kind of misleading as increasing efficiency can result in overfishing, and the implementation of buyback programs or ITQs have hurt communities and their welfare. When economists say to make something more efficient, its the equivalent of telling us to put all our money into one stock as opposed to having a diversified portfolio.

### Allocation of Mangement Agency Resources
Given constraining budgets, several tradeoffs are needed when deciding how to allocate resources, which involve: 1) basic monitoring, 2) the development of new methods and tools, and 3) allocation to enforcement. 

### Synthesis
1. The key goal of fisheries management is to expose tradeoffs and to find a way to successfully manage within the constraints of these tradeoffs.
1. Some patterns in tradeoffs between policy options exist, which include concave, convex, and linear sets. 
1. Suboptimal polices occur because: 1) certain tradeoff calculations have been left out, 2) there are some hidden objectives not captured, and 3) someone isn't doing their job right.
1. Some ways to assess tradeoffs among policy decisions are to create frontier plots as well as form objective functions describing these tradeoffs, which are associated with weights. Maximizing this objective function can help in identifying policy decisions.
1. Some common trade-offs we commonly deal with are shor term vs. long term values (e.g., rebuilding plans), trade-offs between biodiversity and productivity, allocation to resources within management agencies, and edconomic efficiency vs. diverse employment oppurtunities. 


## Strategic Requirements for Sustainable Fisheries